variable "project_name" {}
variable "environment" {}
variable "region" {}
variable "az1" {}
variable "az2" {}
variable "vpc_cidr" {}
variable "public_subnet_az1_cidr" {}
variable "public_subnet_az2_cidr" {}
variable "private_subnet_az1_cidr" {}
variable "private_subnet_az2_cidr" {}
variable "container_port" {}
variable "mongodb_username" {}
variable "mongodb_password" {}